# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paramfittorchdemo',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/paramfittorchdemo',
                'lib_path': 'paramfittorchdemo'},
  'syms': {'paramfittorchdemo.core': {'paramfittorchdemo.core.foo': ('core.html#foo', 'paramfittorchdemo/core.py')}}}